# Generated by Django 5.2.17 on 2026-09-26 03:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=160)),
                ('path', models.CharField(max_length=240)),
                ('read_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'recipient', 'read_at'], name='notificatio_company_7184ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'recipient', 'event_key'), name='notification_idempotency')],
            },
        ),
    ]
