# Generated by Django 5.2.17 on 2026-09-26 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('reviews', '0003_seal_associations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.PositiveIntegerField()),
                ('input_hash', models.CharField(max_length=64)),
                ('input_snapshot', models.JSONField()),
                ('prompt_version', models.CharField(default='stewardship-coach-v1', max_length=40)),
                ('model', models.CharField(max_length=100)),
                ('state', models.CharField(default='QUEUED', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(null=True)),
                ('output', models.JSONField(default=dict)),
                ('provider_response_id', models.CharField(blank=True, max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('decision', models.CharField(blank=True, max_length=12)),
                ('decision_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.membership')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='reviews.review')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'round', 'input_hash'), name='analysis_input_unique')],
            },
        ),
    ]
