# Generated by Django 5.2.17 on 2026-09-26 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('development', '0001_initial'),
        ('reviews', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='commitment',
            name='work_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.workitem'),
        ),
        migrations.AddField(
            model_name='commitmentupdate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.membership'),
        ),
        migrations.AddField(
            model_name='commitmentupdate',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='development.commitment'),
        ),
        migrations.AddField(
            model_name='commitmentupdate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
    ]
