# Generated by Django 5.2.17 on 2026-09-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentupdate',
            name='evidence',
            field=models.ManyToManyField(to='evidence.evidenceitem'),
        ),
    ]
