# Generated by Django 5.2.17 on 2026-09-26 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('NOTE', 'Note'), ('LINK', 'Link'), ('FILE', 'File')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('storage_key', models.CharField(blank=True, max_length=300)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size', models.PositiveIntegerField(default=0)),
                ('validation', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('EXCLUDED', 'Excluded')], default='PENDING', max_length=12)),
                ('validated_at', models.DateTimeField(null=True)),
                ('authorised_excerpt', models.TextField(blank=True)),
                ('validation_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='tasks.workitem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.membership')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_evidence', to='companies.membership')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
