# Generated by Django 5.2.17 on 2026-09-26 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('joined_on', models.DateField(null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('senior_leader', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.department')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='companies.membership')),
                ('job_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organisation.jobrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportingRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reporting', to='organisation.employeeprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='organisation.employeeprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='department_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='jobrole',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='jobrole_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='reportingrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('employee', models.F('manager')), _negated=True), name='no_self_manager'),
        ),
    ]
