# Generated by Django 5.2.17 on 2026-09-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='onboarding_completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
