# Generated by Django 5.2.17 on 2026-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_employeeprofile_onboarding_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar_data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_company',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notification_digest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
