# Generated by Django 5.2.17 on 2026-09-26 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('organisation', '0003_employeeprofile_avatar_data_employeeprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('CAPABILITY', 'Capability'), ('LEGACY', 'Legacy')], max_length=16)),
                ('category', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField(max_length=6000)),
                ('outcome', models.TextField(blank=True, max_length=3000)),
                ('support', models.TextField(blank=True, max_length=3000)),
                ('evidence_url', models.URLField(blank=True)),
                ('shared', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.membership')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_entries', to='organisation.employeeprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
