# Generated by Django 5.2.17 on 2026-09-26 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('expected_outcome', models.TextField()),
                ('type', models.CharField(choices=[('WORK', 'Work'), ('DEVELOPMENT', 'Development')], default='WORK', max_length=20)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('accountable_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountable_work', to='organisation.employeeprofile')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work', to='organisation.employeeprofile')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work', to='organisation.employeeprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tasks.workitem')),
            ],
        ),
        migrations.CreateModel(
            name='WorkUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('blocker', models.TextField(blank=True)),
                ('next_step', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.membership')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='tasks.workitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['company', 'assigned_to', 'status'], name='tasks_worki_company_4bcf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['company', 'due_date'], name='tasks_worki_company_958486_idx'),
        ),
    ]
