# Generated by Django 5.2.17 on 2026-09-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_assign_stewardship_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='declared_employees',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
