# Generated by Django 5.2.17 on 2026-09-26 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('evidence', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='OPEN', max_length=30)),
                ('round', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('conversation', models.JSONField(default=dict)),
                ('hr_assessment', models.JSONField(default=dict)),
                ('employee_ack', models.DateTimeField(null=True)),
                ('manager_ack', models.DateTimeField(null=True)),
                ('finalised_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_reviews', to='organisation.employeeprofile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_reviews', to='organisation.employeeprofile')),
                ('prior_midyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.review')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointed_reviews', to='companies.membership')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField()),
                ('sha256', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='reviews.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('MID_YEAR', 'Mid-Year'), ('YEAR_END', 'Year-End')], max_length=8)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('due_on', models.DateField()),
                ('launched_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.reviewcycle'),
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=60)),
                ('reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.membership')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='reviews.review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager')], max_length=10)),
                ('round', models.PositiveIntegerField()),
                ('content', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.membership')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('evidence', models.ManyToManyField(to='evidence.evidenceitem')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='reviews.review')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reviewcycle',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'kind'), name='two_cycles_per_year'),
        ),
        migrations.AddConstraint(
            model_name='reviewcycle',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['MID_YEAR', 'YEAR_END'])), name='formal_cycle_types'),
        ),
        migrations.AddConstraint(
            model_name='reviewcycle',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='valid_cycle_period'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['company', 'state'], name='reviews_rev_company_96e0f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('cycle', 'employee'), name='one_review_per_employee_cycle'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('employee', models.F('manager')), _negated=True), name='no_self_assessment'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('review', 'kind', 'round'), name='submission_round_unique'),
        ),
    ]
