# Generated by Django 5.2.17 on 2026-09-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_seal_associations'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comparison',
            field=models.JSONField(default=dict),
        ),
    ]
