# Generated by Django 5.2.17 on 2026-09-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='employee_comments',
            field=models.TextField(blank=True),
        ),
    ]
