import fs from 'node:fs';
const file='dist/index.html';
let html=fs.readFileSync(file,'utf8');
html=html.replace('THE NEXT CHAPTER OF LEADERSHIP','BRADLEY EMERSON · BUSINESS ATHLETES');
html=html.replace('Build people who lead with purpose.<br>Create progress that outlasts the finish line.','Corporate training. Executive coaching. Lasting impact.<br>Discover the thinking—and the product—behind it.');
html=html.replace('THE PHILOSOPHY. NOW A PLATFORM.','A STEWARDSHIP PRODUCT CREATED BY BRADLEY EMERSON');
html=html.replace('Bring work, evidence, reflection and development into one connected journey. Designed for people who want their contribution to matter.','Beyond the Finish Line brings Bradley’s stewardship approach into a connected web platform: meaningful work, evidence, human review and development that continues.');
const clients=[['client-1.png','Shangri-La'],['client-2.png','Overseas Realty'],['client-3.jpg','Advantis'],['client-4.png','Litro Gas'],['client-5.jpg','Lanka Talents'],['client-6.png','Daraz'],['client-7.jpg','Pan Asia Bank'],['client-8.jpg','Union Bank'],['client-9.png','K-Tech Trading Group'],['client-10.jpg','Double XL'],['client-11.svg','Finco'],['client-12.jpeg','AMW Capital Leasing']];
const clientSection=`<section class="clients section" aria-labelledby="clients-title"><div class="clients-heading"><p class="eyebrow" id="clients-title">ORGANISATIONS FEATURED BY BUSINESS ATHLETES</p><a href="https://thebusinessathletes.com/" target="_blank" rel="noopener">Explore the client portfolio ↗</a></div><div class="client-grid">${clients.map(([file,name])=>`<div><img src="assets/${file}" alt="${name}" loading="lazy" width="140" height="80"></div>`).join('')}</div><p class="client-note">Business Athletes’ training and coaching portfolio.</p></section>`;
html=html.replace('    <section class="intro section"',clientSection+'\n    <section class="intro section"');
const problem=`<section class="problem-section section" id="why-stewardship"><div class="problem-heading reveal"><p class="eyebrow">THE PROBLEM WE’RE HERE TO SOLVE</p><h2>A year of contribution.<br><span class="muted">Reduced to a number?</span></h2><p>A rating can close a form while leaving the important questions unanswered. What really happened? What is holding someone back? What support will help them grow?</p></div><div class="problem-switcher reveal"><div class="problem-options" role="group" aria-label="Explore the problems stewardship addresses"><button data-problem="0" aria-pressed="true" class="selected"><span>01</span>The score misses the story <i>↗</i></button><button data-problem="1" aria-pressed="false"><span>02</span>Training treats the wrong problem <i>↗</i></button><button data-problem="2" aria-pressed="false"><span>03</span>Knowledge leaves with the person <i>↗</i></button><button data-problem="3" aria-pressed="false"><span>04</span>The review ends. Nothing changes. <i>↗</i></button></div><div class="problem-answer" aria-live="polite"><span class="answer-label">THE STEWARDSHIP RESPONSE</span><h3 id="problem-title">See the contribution.<br>Understand the person.</h3><p id="problem-description">Use specific examples and qualitative assessment to explore current contribution and future potential. Give the employee’s perspective a place in the conversation.</p><div class="problem-result"><span aria-hidden="true">↗</span><p id="problem-result">A clearer basis for the next development decision.</p></div></div></div><p class="framework-note">Based on Bradley’s Stewardship Performance Appraisal approach. The platform supports the process; good judgement and follow-through remain human responsibilities.</p></section>`;
html=html.replace('    <section class="platform-section"',problem+'\n    <section class="platform-section"');
const approach=`<section class="section approach" id="approach"><div class="approach-heading reveal"><p class="eyebrow">WHAT STEWARDSHIP CHANGES</p><h2>A better review asks<br><span class="blue">better questions.</span></h2><p>Bradley’s framework looks at contribution, capability and what a person leaves behind. It gives managers structure for an honest, two-way conversation.</p></div><div class="approach-grid"><article class="approach-card reveal"><span class="value-index">01 / SEE THE WHOLE PERSON</span><h3>Five dimensions.<br>A fuller perspective.</h3><div class="pillar-list"><span>Character</span><span>Contribution</span><span>Capability</span><span>Context</span><span>Continuity</span></div><p>Use observed behaviours and verifiable results. The ECP matrix adds a separate view of current contribution and future potential, without collapsing everything into a single number.</p></article><article class="approach-card diagnostic reveal"><span class="value-index">02 / UNDERSTAND THE GAP</span><h3>Before prescribing support,<br>understand the cause.</h3><p class="equation">Ability <b>×</b> Motivation <b>×</b> Opportunity</p><div class="diagnostic-options" role="group" aria-label="Explore possible execution gaps"><button data-gap="0" class="selected" aria-pressed="true">Ability</button><button data-gap="1" aria-pressed="false">Motivation</button><button data-gap="2" aria-pressed="false">Opportunity</button><button data-gap="3" aria-pressed="false">Role fit</button><button data-gap="4" aria-pressed="false">Management</button></div><p id="gap-description" aria-live="polite">Is there a skill or knowledge gap? Consider coaching, structured learning or an adjustment to the role.</p><small>A conversation framework, not an automatic diagnosis.</small></article><article class="approach-card conversation-card reveal"><span class="value-index">03 / TURN INSIGHT INTO A COMMITMENT</span><h3>Make the next step<br>specific enough to happen.</h3><div class="conversation-tools"><div><strong>Contribution conversation</strong><span>Compare results, impact and expectations.</span></div><div><strong>Capability map</strong><span>Name strengths and the capabilities to build.</span></div><div><strong>Legacy tracker</strong><span>Make mentoring and knowledge transfer visible.</span></div></div><p>Agree 3–5 commitments with owners, support and timelines. Revisit progress in a 90-day check-in, as recommended in the manager’s guide.</p></article></div><div class="approach-end reveal"><span>Not another form to file away.</span><strong>A conversation worth following through.</strong><a class="text-link" href="#contact">Explore stewardship with Bradley ↗</a></div></section>`;
html=html.replace('    <section class="section expertise"',approach+'\n    <section class="section expertise"');
const services=[
['Executive coaching','A focused space to reflect on leadership challenges, clarify your goals and choose the next step with greater confidence.','Executive coaching'],
['Management training','Build management confidence with development shaped around the responsibilities and challenges of your organisation.','Management training'],
['Strategic consulting','Bring business priorities and people’s efforts into alignment, with a clearer direction for the work ahead.','Strategic consulting'],
['Keynotes & speaking','Start a conversation about a keynote or speaking engagement for your organisation’s next gathering.','Speaking engagement'],
['Leadership & talent development','Support emerging and experienced leaders as they build resilience and prepare for greater responsibility.','Leadership development'],
['Culture & engagement','Explore the values, everyday behaviours and shared expectations that shape your workplace.','Culture and engagement'],
['Team coaching','Strengthen the trust, collaboration and accountability that help people work together.','Team coaching']
];
const servicesMarkup=`<div class="service-list reveal">${services.map(([title,desc,subject],i)=>`<details${i===0?' open':''}><summary><span>0${i+1}</span><h3>${title}</h3><i aria-hidden="true">+</i></summary><div><p>${desc}</p><a href="mailto:bradley@thebusinessathletes.com?subject=${encodeURIComponent(subject+' enquiry')}">Discuss this with Bradley ↗</a></div></details>`).join('')}<a class="service-source" href="https://thebusinessathletes.com/services/" target="_blank" rel="noopener">Explore Business Athletes’ services ↗</a></div>`;
html=html.replace(/<div class="service-list reveal">[\s\S]*?<\/div><\/section>/,servicesMarkup+'</section>');
html=html.replace('<p>Work with Bradley through Business Athletes. Start with the challenge your people are facing, then shape the right conversation.</p>','<img class="business-logo" src="assets/business-athletes-logo.png" alt="Business Athletes" width="240" height="80" loading="lazy"><p>Business Athletes is Bradley’s corporate training and coaching practice. Beyond the Finish Line is the stewardship product he created to carry that thinking into everyday work.</p>');
html=html.replace('    <section class="quote-section">',`<section class="programme section"><div class="reveal"><p class="eyebrow">PERSONAL DEVELOPMENT</p><h2>Awaken.<br><span class="muted">Start with self-awareness.</span></h2></div><div class="reveal"><p>Dilini Jayasuriya’s account of Bradley’s Awaken programme describes reflection and self-discovery as a path towards greater awareness and performance.</p><blockquote>“a journey of self discovery to achieve greater self awareness”</blockquote><p class="programme-credit">Dilini Jayasuriya · Director, Breakthrough</p><a href="https://thebusinessathletes.com/about-us/" target="_blank" rel="noopener" class="text-link">Read her experience ↗</a></div></section>\n    <section class="quote-section">`);
html=html.replace('<p>Bradley’s writing extends the conversation into mindset, resilience and the way we choose to grow.</p>','<p>Bradley’s writing extends the conversation into mindset, resilience and the way we choose to grow.</p><img class="books-image" src="assets/bradley-books.png" alt="Bradley Emerson’s books CRAB and PEARL-WISE" loading="lazy" width="1024" height="652">');
html=html.replace('Discover Bradley’s books & writing','Explore the books and their ideas');
const articles=JSON.parse(fs.readFileSync('articles-source.json','utf8').replace(/^\uFEFF/,''));
const labels=['Getting on the Same Page','The Words We Choose','Build on your competitive advantage','The C-suite’s missing perspective','Leadership through uncertainty','The shift from manager to leader','Putting knowledge into practice','Learning from life’s waves','A conversation about workplace performance','Two books, two perspectives','Rethinking educational success','Discover Bradley’s writing','Patterns that avoid accountability','Thinking beyond benchmarks','Developing leaders who go further'];
const insights=`<section class="section insights" id="insights"><div class="insights-heading reveal"><div><p class="eyebrow">FROM BRADLEY’S NOTEBOOK</p><h2>Ideas for a<br><span class="muted">different conversation.</span></h2></div><a class="text-link" href="https://thebusinessathletes.com/blog/" target="_blank" rel="noopener">Visit the original journal ↗</a></div><div class="insight-grid">${articles.slice(0,3).map((a,i)=>`<a class="insight-card reveal" href="${a.url}" target="_blank" rel="noopener"><span class="value-index">${['ALIGNMENT','COACHING','STRATEGY'][i]}</span><h3>${labels[i]}</h3><p>${['What happens when people make their expectations visible to one another?','The language people use can open a different kind of coaching conversation.','Anchor strategy in distinctive strengths while staying aware of the market.'][i]}</p><span class="read-link">Read Bradley’s article ↗</span></a>`).join('')}</div><details class="archive"><summary>Explore the complete article archive <span>15 articles ↗</span></summary><div>${articles.map((a,i)=>`<a href="${a.url}" target="_blank" rel="noopener"><span>${String(i+1).padStart(2,'0')}</span>${labels[i]}<i aria-hidden="true">↗</i></a>`).join('')}</div></details><div class="video-callout reveal"><div><p class="eyebrow">WATCH. REFLECT. TAKE IT FURTHER.</p><h3>Continue the conversation<br>with Bradley.</h3></div><a class="button" href="https://www.youtube.com/@bradleyemerson6467" target="_blank" rel="noopener"><span aria-hidden="true">▷</span>Explore his YouTube channel ↗</a></div></section>`;
html=html.replace('    <section class="contact section"',insights+'\n    <section class="contact section"');
html=html.replace('<p class="contact-location">Colombo, Sri Lanka · Available for corporate enquiries</p>','<p class="contact-location">4D Dickmans Court Apartments, 14 Dickmans Road<br>Colombo 04, Sri Lanka</p><div class="social-links"><a href="https://lk.linkedin.com/in/bradley-emerson-mba-fib-dba-scholar-774045a" target="_blank" rel="noopener">LinkedIn ↗</a><a href="https://web.facebook.com/MrBradleyEmerson/" target="_blank" rel="noopener">Facebook ↗</a><a href="https://www.instagram.com/bradleyemerson.sl/?hl=en" target="_blank" rel="noopener">Instagram ↗</a><a href="https://www.youtube.com/@bradleyemerson6467" target="_blank" rel="noopener">YouTube ↗</a></div>');
fs.writeFileSync(file,html);
console.log('Expanded founder, seven services, 12 clients, problem/solution, framework, books, programme, 15 article links and social contacts.');
