import assert from 'node:assert/strict';import fs from 'node:fs';import worker from './dist/server/index.js';
const files=new Map();const bucket={async get(k){const f=files.get(k);return f?{body:f.value,text:async()=>typeof f.value==='string'?f.value:new TextDecoder().decode(f.value),httpMetadata:f.meta}:null;},async put(k,value,o={}){files.set(k,{value,meta:o.httpMetadata});},async list({prefix}){return{objects:[...files.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key})),truncated:false};}};
const env={GALLERY_ADMIN_EMAIL:'owner@example.test',BUCKET:bucket},base='https://example.test';
const headers={'Origin':base,'oai-authenticated-user-email':'owner@example.test'};
const call=(p,init={},bindings=env)=>worker.fetch(new Request(base+p,init),bindings,{});
assert.equal((await call('/api/gallery',{method:'POST',headers:{Origin:base}})).status,403);
assert.equal((await call('/api/gallery',{method:'POST',headers:{...headers,Origin:'https://attacker.test'}})).status,403);
assert.equal((await call('/studio')).status,302);
assert.equal((await call('/studio',{headers:{'oai-authenticated-user-email':'viewer@example.test'}})).status,403);
assert.equal((await call('/studio',{headers})).status,200);
function form(status='draft',id=''){const f=new FormData();f.set('id',id);f.set('title','QA programme');f.set('description','A local-only test of the publishing workflow.');f.set('host','Test organisation');f.set('status',status);return f;}
const draft=form();draft.set('photos',new Blob([fs.readFileSync('public/assets/training-group.png')],{type:'image/png'}),'photo.png');
let result=await call('/api/gallery',{method:'POST',headers,body:draft});assert.equal(result.status,201);const {post}=await result.json();
assert(!(await (await call('/api/gallery')).json()).posts.some(p=>p.id===post.id),'Draft leaked');
assert.equal((await call(post.photos[0].url)).status,404);
assert.equal((await call(post.photos[0].url,{headers})).status,200);
assert((await (await call('/api/gallery?studio=1',{headers})).json()).posts.some(p=>p.id===post.id));
result=await call('/api/gallery',{method:'POST',headers,body:form('published',post.id)});assert.equal(result.status,201);
assert((await (await call('/api/gallery')).json()).posts.some(p=>p.id===post.id),'Publication missing');
assert.equal((await call(post.photos[0].url)).status,200);
result=await call('/api/gallery',{method:'POST',headers,body:form('archived',post.id)});assert.equal(result.status,201);assert.equal((await call(post.photos[0].url)).status,404);
const invalid=form();invalid.set('photos',new Blob(['<script>bad</script>'],{type:'image/png'}),'fake.png');assert.equal((await call('/api/gallery',{method:'POST',headers,body:invalid})).status,400);
assert.equal((await call('/api/contact',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:'{}'})).status,503);
const originalFetch=globalThis.fetch;let email;
globalThis.fetch=async(url,init)=>{assert.equal(url,'https://api.resend.com/emails');email=JSON.parse(init.body);return Response.json({id:'mock'});};
const mailEnv={...env,RESEND_API_KEY:'test-only',CONTACT_FROM:'Website <test@example.test>'};
result=await call('/api/contact',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({name:'Test Person',email:'reply@example.test',company:'Test',interest:'Platform',message:'This is a mocked email delivery test.'})},mailEnv);assert.equal(result.status,200);assert.deepEqual(email.to,['bradley@thebusinessathletes.com']);assert.equal(email.reply_to,'reply@example.test');
globalThis.fetch=originalFetch;
console.log('Passed: owner access, cross-origin rejection, upload validation, draft privacy, publish/archive, gallery persistence contract and mocked email routing. No live email sent.');
