import fs from 'node:fs';
const assets = [
 ['912f739c-58f7-44bf-84f0-189a486111f2','book-beyond.png'],
 ['cb66326f-07bc-4a64-b88b-8ba43db39ab2','business-athletes-logo.png'],
 ['6a8ba0f1-714b-41d6-bdae-101e9d761cc7','book-awaken.png'],
 ['87d7816c-822b-4795-8ef0-58e1e4baf1cb','book-pearl-wise.png'],
 ['cb170ace-a38e-4a9d-b67a-d258772fb64e','book-crab.png']
];
for(const [id,name] of assets)fs.copyFileSync(`C:/Users/danus/AppData/Local/Temp/codex-clipboard-${id}.png`,`dist/assets/${name}`);
let html=fs.readFileSync('dist/index.html','utf8');
const start=html.indexOf('<section class="section perspectives"');
const end=html.indexOf('<section class="section insights"',start);
const books=[
 ['book-beyond.png','Beyond the Finish Line','Goals, grit and what comes next.','THE BOOK BEHIND THE NAME'],
 ['book-awaken.png','Awaken','A book by Bradley Emerson.','A DIFFERENT PERSPECTIVE'],
 ['book-pearl-wise.png','PEARL-WISE','Wisdom and experience, one pearl at a time.','WISDOM & EXPERIENCE'],
 ['book-crab.png','CRAB','Explore the habits that hold us back.','MINDSET & GROWTH']
];
const section=`<section class="section perspectives" id="perspectives"><div class="author-image reveal"><img src="assets/bradley-library.png" alt="Bradley Emerson in front of a library of books" loading="lazy" width="1122" height="1402"><div class="author-label"><span>THE AUTHOR</span><strong>A different way<br>to see what’s next.</strong></div></div><div class="author-copy reveal"><p class="eyebrow">FOUR BOOKS. AN ONGOING CONVERSATION.</p><h2>Beyond the room.<br><span class="muted">Beyond the moment.</span></h2><p>Bradley’s writing invites you to pause, question and look at what comes next with a different perspective.</p><p>Explore <em>Beyond the Finish Line</em>, <em>Awaken</em>, <em>PEARL-WISE</em> and <em>CRAB</em>—four books by Bradley Emerson.</p><div class="book-platform-note"><span>FROM IDEAS TO EVERYDAY PRACTICE</span><p><strong>Beyond the Finish Line is a book—and a stewardship platform.</strong> The book explores goals, grit and what comes next. The platform brings work, evidence, review and development into one connected journey.</p><a class="text-link" href="#platform">Explore the stewardship platform ↗</a></div></div><div class="book-shelf">${books.map(([img,title,description,label],i)=>`<a class="book-card reveal" href="mailto:bradley@thebusinessathletes.com?subject=${encodeURIComponent('Enquiry about '+title+' — the book')}" aria-label="Enquire about ${title}, the book"><div class="book-cover-stage book-tone-${i}"><img src="assets/${img}" alt="${title} book cover by Bradley Emerson" loading="lazy"></div><div class="book-card-copy"><span class="book-category">${label}</span><h3>${title}</h3><p>${description}</p><span class="book-enquire">Enquire about this book <i aria-hidden="true">↗</i></span></div></a>`).join('')}</div></section>\n`;
html=html.slice(0,start)+section+html.slice(end);
html=html.replace('Bradley Emerson in a navy suit, photographed with cinematic studio lighting','AI-styled cinematic portrait of Bradley Emerson in a navy suit');
fs.writeFileSync('dist/index.html',html);
fs.appendFileSync('dist/styles.css',`\n/* Author collection: supplied covers stay intact, with a subtle physical-book lift. */\n.perspectives{row-gap:54px}.perspectives .author-image{height:480px}.business-logo{width:240px;height:114px;object-fit:cover;object-position:center}.book-platform-note{margin-top:30px;border-left:2px solid var(--blue);padding-left:22px}.book-platform-note>span{font-size:9px;letter-spacing:.13em;color:var(--blue)}.book-platform-note p{color:var(--muted);font-size:13px;line-height:1.85;margin-top:15px}.book-platform-note strong{color:var(--ink);font-weight:500}.book-platform-note .text-link{font-size:12px}.book-shelf{grid-column:1/-1;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:24px}.book-card{min-width:0}.book-cover-stage{height:310px;display:flex;align-items:center;justify-content:center;padding:28px;background:#eff4f8;border-radius:12px;perspective:900px;overflow:hidden}.book-cover-stage img{height:100%;max-width:100%;object-fit:contain;box-shadow:8px 12px 20px #14254125;transform:rotateY(-9deg) rotateZ(-2deg);transition:transform .6s var(--ease),box-shadow .6s}.book-card:hover img,.book-card:focus-visible img{transform:translateY(-8px) rotateY(0deg);box-shadow:12px 22px 28px #14254130}.book-tone-1{background:#ececef}.book-tone-2{background:#e9f5f7}.book-tone-3{background:#f6f1ef}.book-card-copy{padding:23px 2px 0}.book-category{font-size:8px;letter-spacing:.13em;color:#7b8fae}.book-card h3{font-size:22px;font-weight:520;letter-spacing:-.035em;line-height:1.2;margin:12px 0}.book-card p{font-size:12px;color:var(--muted);line-height:1.7;min-height:42px;margin-bottom:20px}.book-enquire{font-size:11px;color:var(--blue);display:flex;justify-content:space-between;gap:10px;border-top:1px solid var(--line);padding-top:15px}.book-enquire i{font-style:normal}.motion-paused .book-cover-stage img{transition:none}@media(max-width:1000px){.book-shelf{gap:18px}.book-cover-stage{height:255px;padding:20px}.book-card h3{font-size:19px}}@media(max-width:680px){.book-shelf{grid-template-columns:repeat(2,minmax(0,1fr));gap:30px 18px}.book-cover-stage{height:220px;padding:18px}.book-card-copy{padding-top:18px}.book-category{font-size:7px}.book-card h3{font-size:19px}.book-card p{font-size:11px;min-height:55px}.book-enquire{font-size:10px;line-height:1.5}.perspectives .author-image{height:420px}}@media(prefers-reduced-motion:reduce){.book-cover-stage img{transition:none!important}.book-card:hover img,.book-card:focus-visible img{transform:none}}\n`);
